# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snake.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bsnake.proto\x12\x05snake\"\x1c\n\x0bObservation\x12\r\n\x05\x62oard\x18\x01 \x03(\x05\"b\n\x06\x41\x63tion\x12$\n\x03\x64ir\x18\x01 \x01(\x0e\x32\x17.snake.Action.Direction\"2\n\tDirection\x12\x06\n\x02UP\x10\x00\x12\t\n\x05RIGHT\x10\x01\x12\x08\n\x04\x44OWN\x10\x02\x12\x08\n\x04LEFT\x10\x03\",\n\x0bStepRequest\x12\x1d\n\x06\x61\x63tion\x18\x01 \x01(\x0b\x32\r.snake.Action\"U\n\x0cStepResponse\x12\'\n\x0bobservation\x18\x01 \x01(\x0b\x32\x12.snake.Observation\x12\x0e\n\x06reward\x18\x02 \x01(\x01\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\"\x0e\n\x0cResetRequest\"8\n\rResetResponse\x12\'\n\x0bobservation\x18\x01 \x01(\x0b\x32\x12.snake.Observation2l\n\x05Snake\x12/\n\x04Step\x12\x12.snake.StepRequest\x1a\x13.snake.StepResponse\x12\x32\n\x05Reset\x12\x13.snake.ResetRequest\x1a\x14.snake.ResetResponseB\x0f\xaa\x02\x0cSnakeRL.Grpcb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'snake_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\014SnakeRL.Grpc'
  _OBSERVATION._serialized_start=22
  _OBSERVATION._serialized_end=50
  _ACTION._serialized_start=52
  _ACTION._serialized_end=150
  _ACTION_DIRECTION._serialized_start=100
  _ACTION_DIRECTION._serialized_end=150
  _STEPREQUEST._serialized_start=152
  _STEPREQUEST._serialized_end=196
  _STEPRESPONSE._serialized_start=198
  _STEPRESPONSE._serialized_end=283
  _RESETREQUEST._serialized_start=285
  _RESETREQUEST._serialized_end=299
  _RESETRESPONSE._serialized_start=301
  _RESETRESPONSE._serialized_end=357
  _SNAKE._serialized_start=359
  _SNAKE._serialized_end=467
# @@protoc_insertion_point(module_scope)
